name: build push image

on:
  push:
    branches:
      - "main"
    paths:
      - 'Dockerfile'
      - 'requirements.txt'
    paths-ignore:
      - 'README.md'

jobs:
  build_push:
    permissions:
      contents: read
      packages : write

    env:
      IMAGE_NAME: ${{ vars.GCP_REGION}}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID}}/${{ vars.GCP_REPOSITORY}}/${{ vars.PROJECT_NAME }}-function

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
